[pytest]
addopts = --html=reports/reporte.html --self-contained-html
markers =
    regression: Tests de regresión críticos
    smoke: Tests de humo para verificar funcionalidades básicas
    login: Tests relacionados con el proceso de inicio de sesión
    catalog: Tests relacionados con el catálogo de productos
    cart: Tests relacionados con el carrito de compras
    e2e: Test de flujo completo end to end
    api: Tests de API REST